### ISSUE TITLE
broken  python setup.py develop

### ISSUE THREAD

**Issue by marregui** [shapelets/shapelets-compute#13]
Having followed the installation guide, upon executing command:

**python setup.py develop**

(Python 3.7.9)

Result:

```
random.cpp
signal_processing.cpp
statistics.cpp
C:\Program Files\ArrayFire\v3\lib\af.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x368 [C:\Users\Me\workspace\shapelets-compute\build\temp.win-
amd64-3.7\Release\modules\pygauss\PyGauss.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 219, in <module>
    setup_package()
  File "setup.py", line 215, in setup_package
    setup(**meta)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 161, in run
    develop.run(self)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 104, in run
    self.build_extension(ext)
  File "setup.py", line 149, in build_extension
    cwd=self.build_temp)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'PyGauss', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
```

**Comment by marregui** [comment]
Python 3.7.9

**Comment by marregui** [comment]
this was a problem of incompatibility with the system installed ArrayFire version. By uninstalling it, the command works as expected.
